### ISSUE TITLE
Visibility and Coordinate Conversion crashing when invalid coordinates pasted 

### ISSUE THREAD

**Issue by BobBooth** [Esri/visibility-addin-dotnet#309] opened 2018-12-10 20:48 UTC
Testing the latest build of the Visibility and Coordinate Conversion stand alone add-ins, on Pro (2.3.0_15735) and ArcMap (10.3.1) I have found a crash when certain values are pasted into the input box (the addins work fine for adding points by clicking on the map).

If I set the coordinate system for the map  by adding the "ElevationUTM_Zone10" from solutions test catalog data, in MilitaryToolsTestData.gdb and click on the map with the identify tool, I get values in our AOI such as:
(in ArcMap)
647,071.585  4,037,740.468 Meters
647,771.497  4,035,832.642 Meters 
or
(in Pro)
624,927.73E 4,045,489.61N m
627,776.94E 4,043,909.37N m
![image](https://user-images.githubusercontent.com/3801392/49758634-81055a00-fc8d-11e8-8502-e34162279e6b.png)

DD and UTM values do not crash.

If I use these values as inputs for the LLOS, RLOS, and Coordinate Conversion input boxes, ArcGIS Pro (daily 2.3.0_15735), and ArcMap (10.3.1) both crash.
I installed the previous versions of the addins [server]\Commercial\Solutions\DefenseSolutions and tested the September, August, and June 2018 builds. September and August had the crash, but the latest June build does not.

**Comment by BobBooth** [comment] 2018-12-10 20:55
@kgonzago @dfoll @lfunkhouser @csmoore  - coordinate conversion crash found, also affects visibility The 10/16/18 build of Distance and Direction (in December2018) is not affected.

**Comment by BobBooth** [comment] 2018-12-12 18:14
Opened issue https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/547
Closing this one.

**Comment by csmoore** [comment] 2018-12-28 21:16
I was not able to reproduce a crash in coordinate-conversion-addin-dotnet - but I was able to identify a possible source of the crash in Visibility. 

Reopening issue and addressed in PR #310

**Comment by dfoll** [comment] 2019-01-02 14:11
Tested using Visibility build 32 build from this [feature branch](https://github.com/Esri/visibility-addin-dotnet/tree/csm/309-crash-on-invalid-coord)

With ArcGIS Pro 2.3.0.15723 the add-in will not accept invalid coordinates, so you cannot attempt to run an analysis, and there is no crash
![image](https://user-images.githubusercontent.com/5322669/50595442-51053d00-0e6e-11e9-8f63-2be4b21863d7.png)

**Comment by BobBooth** [comment] 2019-01-02 15:37
![image](https://user-images.githubusercontent.com/3801392/50598928-52d4fd80-0e7a-11e9-93cb-0272d5dfaa20.png)

**Comment by csmoore** [comment] 2019-01-02 15:38
@dfoll @BobBooth - I can reproduce and see the issue, I will add to the PR #310 in a few mins

**Comment by csmoore** [comment] 2019-01-02 15:45
@dfoll @BobBooth - PR #310 has been updated for ArcMap - please retest - sorry, not sure how I missed that

**Comment by BobBooth** [comment] 2019-01-02 16:33
This works with latest test build in ArcMap.

**Comment by dfoll** [comment] 2019-01-02 16:58
Rebuilt MT (176) with the recent changes and this looks good

**Closed** 2019-01-14 16:22 UTC
Labels: A-bug, B-high, E-verified, S-Coordinate Conversion, S-Military Tools, V -  Pro 2.1, V - 10.3.1
