### ISSUE TITLE
Construct SightLines fails in ArcGIS Pro 2.0

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#181] opened 2017-03-30 20:34 UTC
When using the visibility add-in the tool fails to create the sight lines.  The public string ObserversLayerName does not seem to be getting the correct path to allow this fc to be written to the database. I used the ArcGIS Pro 2.0 branch.

**Comment by csmoore** [comment] 2017-03-30 21:28
When Lyle & I looked at this, it looked like all of the tools that use/reference "LLOS_Observers" "LLOS_Targets" where not using the fully-qualified path, just the Name.

Not sure why this would break now, but we can probably fix by just adding CoreModule.CurrentProject.DefaultGeodatabasePath to the name.

**Comment by csmoore** [comment] 2017-06-14 00:30
I think this was just a bug in an early version of Pro 2.0 - I can't seem to repro - can you retest?

**Comment by NatalieCampos** [comment] 2017-06-14 20:41
unable to reproduce original error. Closing issue.

**Closed by NatalieCampos** 2017-06-14 20:41 UTC
Labels: 3 - Verify, B - Bug
