### ISSUE TITLE
RLOS - Cutting off viewsheds when a user brings in a non projected data layer

### ISSUE THREAD

**Issue by joebayles** [Esri/visibility-addin-dotnet#242] opened 2017-11-01 18:28 UTC
**Situation:** 
When a user adds a non projected layer to the map first it is setting something that the add-in will use for that project going forward. Currently here are the steps to replicate: 

1. Start with a new project with a map
2. Bring in a set of data that is not projected
3. Try and run the Vis RLOS tool and you will get the error of the data not being projected.
4. Add another elevation layer that is projected and you try to run the tool, but first make sure to clear the points in the RLOS tool.
5. The results will return with the ends chopped off
6. 
**Background:** 
Users use data from multiple sources and receive that data in a variety of ways. that data comes in projected and non projected formats. We will not be able to control what data sets our users use in our projects. 
**Current State using the workflow from above:** 
![image](https://user-images.githubusercontent.com/5488313/36873216-a9a39ece-1d5c-11e8-828b-ac61e55ecc8b.png)

Definition of Done: 
When a user has multiple types of spatial data in their data frame the add-in only cares about the source that the add-in is pointing to in order to conduct the analysis. 

**Original Issue Full Background:** 
During work on ACS, assessed RLOS using DTED and SRTM data multiple times with the same results.

Regardless of size, location, or how many, the left and right sides of the 360° RLOS results are cut off:

**Multiple 360° Viewshed out to 5000m on DTED:**
**Single 360° Viewshed out to 5000m on DTED and SRTM:**
**Multiple 360° Viewshed out to 1000m on DTED and SRTM:**

Regardless of size, location, or angle, it will not display a <360° RLOS result.
**Multiple 45° Viewshed out to 1000m on DTED and SRTM:**
_Ran this result multiple times, across the 0° mark; multiple and single points, different azimuths, angles, and distances. No result._

#### Edit: Removed Screenshots

**Comment by BobBooth** [comment] 2017-11-01 18:46
@joebayles - I wonder if it is related to this issue that I was seeing:
https://github.com/Esri/visibility-addin-dotnet/issues/169

**Comment by topowright** [comment] 2017-11-02 21:39
I am having different results than @joebayles and @nfeuerstein. I see the following: 
![image](https://user-images.githubusercontent.com/5488313/32351666-692e33c4-bfdb-11e7-8864-10f602aaa155.png)

I show that this is my install information for the add-in: 
![image](https://user-images.githubusercontent.com/5488313/32351683-8058c23a-bfdb-11e7-8855-cf18dfa7f363.png)


I am going to check the current 2.0 download of Military Tools and see if I get the same results

**Comment by Dbarnes1** [comment] 2017-11-02 23:03
I'm on released and I ran default settings and I got this: 
![image](https://user-images.githubusercontent.com/13024357/32354401-d4328ed0-bfe6-11e7-8dcc-0649b84b3c70.png)

Then I tried with a fan and got this: 
![image](https://user-images.githubusercontent.com/13024357/32354524-4cb9f816-bfe7-11e7-8433-eb74161ff111.png)

Running it on Pro 2.0, but not a fresh install or pro project by any means. I'm using the project and raster data that I've been demonstrating since FedGIS 2017.

**Comment by topowright** [comment] 2017-11-02 23:13
I wonder if there is something being cached when we move from one an old add-in to a new one. I am not working on a fresh install, but I did download our current release and received good results from the 360 radius and by setting  a FoV. @jmccausland could this be a problem with an older version being present and not installing the newest version?

**Comment by joebayles** [comment] 2017-11-06 03:54
Assigning to me, I'll check version in the morning.

**Comment by joebayles** [comment] 2017-11-06 21:18
![image](https://user-images.githubusercontent.com/5016557/32464471-025a6100-c2f5-11e7-843c-f7996943232a.png)

**Comment by Dbarnes1** [comment] 2017-11-09 16:29
So we did some testing against this last night and @elinz realized what the issue was. In the gp environments dialog, under Processing Extent. We need to update the default processing extent of the visibility add-in so that it is large enough that it won't clip the output layers. 

![image](https://user-images.githubusercontent.com/13024357/32616652-b2aa1274-c527-11e7-9606-e467a1ff44c9.png)

In the mean time, we should document this issue and the workaround, changing the processing extent from "default" to "current display extent"

**Comment by joebayles** [comment] 2017-11-09 18:31
Here's an additional screenshot I took so I could write what Dan wrote above. Unassigning myself.

![image](https://user-images.githubusercontent.com/5016557/32622848-1efd3148-c539-11e7-896a-77487dc8e36b.png)

**Comment by topowright** [comment] 2017-11-29 23:33
This issue should be addressed by core documentation. 

http://pro.arcgis.com/en/pro-app/tool-reference/environment-settings/output-extent.htm

We should attempt to not rewrite documentation that is already avaiable in core.

**Comment by joebayles** [comment] 2017-11-30 00:01
Agreed, but if it baffled enough people on our team, I imagine it will do something similar to our users. 

Suggest adding a note to the Visibility documentation.

**Comment by topowright** [comment] 2017-11-30 16:48
This is the statement that has been added to the documentation: 

If the  polygons for RLOS have  ends that  have been cut off, check your geoprocessing environment variables. It could be set to something other than default, which would create this result.

**Comment by nfeuerstein** [comment] 2017-11-30 17:20
@topowright with the setting set at "default" we are getting those results: the ends cut off.

**Comment by topowright** [comment] 2017-11-30 17:57
@nfeuerstein when we get a chance lets sit together and look at this issue. Not sure how to reproduce it on my end and its confusing if that did not fix your issue.

**Comment by topowright** [comment] 2017-12-01 00:01
Did some more testing today and this is what I can replicate: 

With using the 

![image](https://user-images.githubusercontent.com/5488313/33461519-ab934106-d5e7-11e7-8eea-abc8da8b8e67.png)

**Comment by topowright** [comment] 2017-12-01 00:05
**With the Default set:** 
![image](https://user-images.githubusercontent.com/5488313/33461643-35528bb8-d5e8-11e7-8f9f-ea1f01828994.png)

**Comment by topowright** [comment] 2017-12-05 08:15
I have ran the add-in 20 times and had no luck seeing this issue: 
![image](https://user-images.githubusercontent.com/5488313/33596641-3933a9da-d951-11e7-8106-90cdeb26e7ff.png)
Closing the issue.

**Comment by topowright** [comment] 2017-12-12 20:21
I can now reproduce this issue in ArcGIS Pro 2.1. Gathering info to figure out the problem now.

**Comment by joebayles** [comment] 2017-12-12 21:25
@topowright, as far as I can tell, the issue is that either default extent isn't honoring the tool output, or the tool somehow is looking at another processing extent.

When @nfeuerstein and I ran it, we ran it on Default and got the cutoff results. We forced the geoprocessing extent to change by specifying something different/specific_(not the ideal workflow, but a workaround)_.

When you ran it, it defaulted correctly for you, but then you specified something specific that cut off your results. I think your repro is related, but not the same, as ours.

![image](https://user-images.githubusercontent.com/5016557/33909256-e309702c-df3f-11e7-92fc-70b553236592.png)

**Comment by elinz** [comment] 2017-12-12 21:58
@topowright @joebayles @nfeuerstein According to the environment doc shown above, if you are using the default extent, then the tool will determine the processing extent. Seems like the core gp tool that is executed is not calculating this correctly. Definitely something to talk to the gp team about. We may need to be proactive here and calculate what the extent produced by the tool should be and set that through code before the RLOS is run. Then set the extent environment back to what it was originally before running the tool.

**Comment by BobBooth** [comment] 2018-01-04 16:54
I reached out to the raster team, am emailing with Xuguang Wang, trying to get their ideas.

**Comment by lfunkhouser** [comment] 2018-01-05 19:29
This issue is not consistency reproduced. We are going to keep this issue open to capture the follow up with the Raster team and bring it in when it is understood.

**Comment by BobBooth** [comment] 2018-01-09 20:45
Not sure how your mask feature class is created under the hood, but please check if the spatial references of the observer points, raster surface, and the mask feature class are all the same when the mask is created and when the visibility calculation happens.

In this case, actually a mask might not be needed. You could set a outer radius when executing the Visibility tool and achieve similar results.

Thanks,
Xuguang

**Comment by topowright** [comment] 2018-01-24 21:03
@BobBooth have you looked into any of the things that Xuguang has pointed out might be an issue?

**Comment by BobBooth** [comment] 2018-01-24 21:14
@topowright - I looked at the code, but from what I could tell, it was inheriting the spatial reference from the surface. I would like for a dev to look into this further.
@csmoore  @adgiles @kgonzago

**Comment by csmoore** [comment] 2018-01-24 22:02
The Spatial References should all be the same (For Map, Surface, Points, Mask)

Just curious if this issue is only occurring when RLOS is 360°?  Or if it be replicated in the GP tools?

**Comment by topowright** [comment] 2018-01-25 09:07
I have now found the processes to reporduce this error. 

1. Start with a new project with a map
2. Bring in a set of data that is not projected
3. Try and run the Vis RLOS tool and you will get the error of the data not being projected. 
4. Add another elevation layer that is projected and you try to run the tool, but first make sure to clear the points in the RLOS tool. 
5. The results will return with the ends chopped off


**Problem:** 
What seems to be the possible issue is that the vector points that are being collected and passed through the gp tool for the add-in are not liking the spatial reference that is being given to them. We need to possibly reproject the incoming center points before we run the analysis. The reproject could be based on the source elevation layer. 

![image](https://user-images.githubusercontent.com/5488313/35379709-d282829a-016b-11e8-9192-b4e605cfc10d.png)

**Comment by topowright** [comment] 2018-01-25 09:08
@csmoore I think now that i have the workflow on how to reproduce I can try it in ArcGIS Pro using the GP Tools.

**Comment by topowright** [comment] 2018-03-01 22:21
Running thru certification testing I have verfired that this is still and issue in ArcGIS Pro 2.2: 
![image](https://user-images.githubusercontent.com/5488313/36872943-d5c0aca0-1d5b-11e8-9182-7e9dd00467c8.png)

**Comment by topowright** [comment] 2018-06-22 06:21
Talking with the pro team it seems like this is something that we have done incorrectly in our implementation and it is not a core problem. Based on that idea I am removing the blocked label.

**Comment by topowright** [comment] 2018-08-01 16:56
This issue has been fixed by the addition of a spatial check done before the analysis is conducted. This is what happens now when attempting to run the addin with bad data. 

![image](https://user-images.githubusercontent.com/5488313/43536318-24b01af2-9571-11e8-8b63-a30870f70120.png)

**Comment by topowright** [comment] 2018-08-01 16:56
closing this issue.

**Closed** 2018-08-10 00:07 UTC
Labels: A-bug, B-high, CyberTech, E-verified, V -  Pro 2.1, V - MT 3.1
