### ISSUE TITLE
Visibility Add-in does not support remote elevation service

### ISSUE THREAD

**Issue by ljuru** [Esri/visibility-addin-dotnet#328] opened 2019-06-27 21:54 UTC
## Description:
Currently the Visibility Add-in in Military Tools does not support remote elevation service

## Expected Result:
A server publisher connection needs to be created in order to run this tool. 

Additional Notes:
Discovered during Certification Testing for the Visibility Addin 
Observed in ArcMap 10.7.1 and ArcGIS Pro 2.4

Note: related to #194

**Comment by dfoll** [comment] 2019-08-09 12:52
we need to try to repro this one for @CTLocalGovTeam . @CTLocalGovTeam was not able to reproduce with [this image service](http://lidar.geodata.md.gov/imap/rest/services/Allegany/MD_allegany_dem_m/ImageServer). We should confirm if this is still an issue with a different image service, so that we can determine the difference and @CTLocalGovTeam can help with a fix

**Comment by dfoll** [comment] 2019-08-16 15:23
Took a look at this to assist with the work we asked @CTLocalGovTeam. I can confirm That with the [image service CT referenced](http://lidar.geodata.md.gov/imap/rest/services/Allegany/MD_allegany_dem_m/ImageServer) the add-in does run. I believe what was being referenced in the original issue is the amount of time it takes for the analysis to run. Using this image service the analysis for one observer and one point took approximately 5 minutes over a connection with bandwith on the slower side.

![image](https://user-images.githubusercontent.com/5322669/63178556-46bc3b80-c018-11e9-97c6-1163ed6cd418.png)

**Comment by dfoll** [comment] 2019-08-16 20:41
We will be closing this because it is an incorrect claim. The functionality does work, performance is the problem we need to look at. Continuing to look at performance for the Visbility add-in will be continued on issue #194

**Closed** 2019-08-16 20:43 UTC
Labels: A-feature, E-non reproducible, S-Military Tools
