### ISSUE TITLE
BUG-000107342  There is a typographical error in Viewshed.py script from the Military Tools for ArcGIS 10.5.1

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#223] opened 2017-08-24 18:18 UTC
<div><div>
<span><b>Salesforce ID:</b> BUG-000107342</span><br/>
<span><b>Salesforce Submitter:</b> Emad Mohammed</span><br/>
<span><b>Salesforce Submit Date:</b> 8/14/2017 9:06 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Defense</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 2.0 Beta</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

Steps to Repro:
Using Military Tools for ArcGIS 2.0 with Portal/Server 10.5.1 when setting up the visibility geoprocessing service on a closed system, the user noticed a small typo in the Viewshed.py script.
The typo is on line 183, and reads: arcpy.env.mask = "in_memory\\OutBuffer"
It should read: arcpy.env.mask = "in_memory\\OuterBuffer". The "er" is missing from the end of the line between "Out" and "Buffer".
Kindly refer to the following link: 
https://solutions.arcgis.com/defense/help/military-tools/web-appbuilder/set-up-elevation-geoprocessing-service.htm

**Comment by joebayles** [comment] 2017-08-31 18:25
Has anyone talked about this? What is the typographical error?

**Comment by topowright** [comment] 2017-12-15 10:12
I have verified that this was fixed in Military Tools for ArcGIS 1.1, which was released in June 2017

**Comment by lfunkhouser** [comment] 2017-12-19 22:26
@topowright This issue was reported on Military Tools for ArcGIS 2.0 - was it an issue at 1.0, fixed at 1.1 but reintroduced at 2.0?

**Comment by csmoore** [comment] 2017-12-20 13:44
I wasn't aware of us fixing this until #246 - https://github.com/Esri/visibility-addin-dotnet/pull/246/files - I wasn't aware there was an open issue associated with this, so sorry for not linking to this in the PR

**Comment by topowright** [comment] 2017-12-21 08:39
@joebayles the issue was a typo where we were missing the er in the word outer. 
@lfunkhouser the issue is present in 1.1 and 2.0. My mistake on the comment above. The issue has been fixed based on the pull request referenced by @csmoore above.

**Closed** 2017-12-21 17:16 UTC
Labels: E-verified, Support

**Comment by lfunkhouser** [comment] 2017-12-29 21:33
Comment to support: This is verified as fixed and will be fixed in the next release of Visibility and Military Tools for ArcGIS.
