### ISSUE TITLE
BUG-000105198  The Clear Graphics button does not work on the Visibility tool from the Military tools for ArcGIS solution

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/visibility-addin-dotnet#199] opened 2017-05-24 19:36 UTC
<div><div>
<span><b>Salesforce ID:</b> BUG-000105198</span><br/>
<span><b>Salesforce Submitter:</b> Sarah Bubka</span><br/>
<span><b>Salesforce Submit Date:</b> 5/16/2017 3:10 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000105198</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Pro</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 1.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by csmoore** [comment] 2017-05-24 19:46
Duplicate of #157 #154 - assigning for verification

**Comment by NatalieCampos** [comment] 2017-05-24 21:17
Verified. Other issues were closed.

**Closed by NatalieCampos** 2017-05-24 21:17 UTC
Labels: 3 - Verify, B - Duplicate, Support
