### ISSUE TITLE
RLOS on image service fails with "calculation cancelled" message

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#184] opened 2017-04-28 13:38 UTC
_From @BobBooth on March 1, 2017 19:42_

I have added an image service of elevation data to my map.
(data at: http://navigator.state.or.us/arcgis/services  /Framework/Elevation_DEM_10)
I can run the Military Tools Add-In LLOS tool against it and it works (two points separated by 10,000 meters).
When I run the Military Tools Add-In RLOS against it (default values 1000 m distance, 2m height), I get a message box titled "Calculation cancelled" which says "Results not calculated. Check Input parameters and try again."
![image](https://cloud.githubusercontent.com/assets/3801392/23477649/a4cc8acc-fe8c-11e6-8cd7-bb14a594fb59.png)

### Expected Behavior
I would expect the tool to use the elevation data as it would a local layer. The LLOS tool does.

### Steps to Reproduce (for bugs)
Add image service of elevation data. (data at: http://navigator.state.or.us/arcgis/services  /Framework/Elevation_DEM_10)
Open LLOS tab. Add two points 10,000 meters apart. Accept defaults, click OK, get correct results.
Open RLOS tab. Add single point (in my case, near the midpoint of the previous two). Accept defaults. Click OK, get error message.

### Your Environment
ArcMap 10.4.1
Military Tools Add-in  build 1228
(03-01-2017_1228)

_Copied from original issue: Esri/military-tools-desktop-addins#8_

**Comment by lfunkhouser** [comment] 2017-04-28 13:38
_From @kgonzago on March 2, 2017 14:37_

@csmoore can you look into this when convenient?

**Comment by lfunkhouser** [comment] 2017-04-28 13:38
_From @csmoore on March 2, 2017 14:55_

I was able to repro this - the bug is [here](https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/Visibility/ArcMapAddinVisibility/ViewModels/RLOSViewModel.cs#L987) (needs to also check for ImageServiceLayer)

**Comment by BobBooth** [comment] 2017-04-28 20:07
@topowright - that was the one I saw the problem with. I think @csmoore reproduced it with an east coast DEM image service.

**Comment by topowright** [comment] 2017-04-28 20:10
@csmoore can you share the service that you tested against?

**Comment by BobBooth** [comment] 2017-04-28 20:10
@topowright - the service seems to be running. I had a user connection to it in ArcMap and it is displaying.
![image](https://cloud.githubusercontent.com/assets/3801392/25545527/3be48356-2c2d-11e7-8ee2-8e5854c922c3.png)

**Comment by topowright** [comment] 2017-04-28 20:12
I have tried to bring that same service up in a browser with no luck. Can you copy the link one more time. Also, check and see if you get the same result in a browser?

**Comment by BobBooth** [comment] 2017-04-28 20:13
![image](https://cloud.githubusercontent.com/assets/3801392/25545561/7048cfa8-2c2d-11e7-8039-4eee6a163dff.png)
http://navigator.state.or.us/ArcGIS/services

**Comment by BobBooth** [comment] 2017-04-28 20:17
Looks like their server (Apache) is rejecting simple web connections to it, even though it is available through an ArcGIS Server connection in ArcMap.

**Comment by topowright** [comment] 2017-04-28 20:28
I am able to get the service to open in ArcMap, but not is a browser. Not sure if that is an issue.

I am seeing the same issue you are.

The tool should throw the error on both the LLOS and RLOS if the underline projection is the reason; however, it does not. I think we should test against a image service that is projected and see if we get the same results.  This is something that we would have to stand up because I do not know of a service that is already shared this way.  

State Plane Coordinate System (SPCS) is not a projection (also known as SPC, State Plane, and State).

I might be off on this one, but I think this is why the problem is happening. The problem should be resolved with RLOS returning information about the service not being in the correct projection.

**Comment by topowright** [comment] 2017-05-05 18:11
@NatalieCampos I would like you help on this.

**Comment by csmoore** [comment] 2017-05-17 19:58
The original bug that caused the tool to abort has been addressed in #188 , 

I tested this with a service covering a smaller area at: https://nationalsecurity.esri.com/portal/home/item.html?id=7cf1f1dd0a6f4858a6ffacd3d2f7d0d0 

The larger issue of the tool taking an extremely long time to complete for a service covering a large area and/or higher resolution is still an issue (I'll open a new one once the bug part is verified). To mitigate , or at least warn the user about this, a warning was added when using an image service: **"The selected input surface layer is an Image Service and make take a long time to process. Do you wish to continue?"**

**Comment by NatalieCampos** [comment] 2017-05-17 20:25
@csmoore would it be possible to only process the visiblity in memory at the image display resolution rather then the source resolution.  Similar to how the raster functions work.

**Comment by NatalieCampos** [comment] 2017-05-17 22:45
When using an image service, the following dialog is thrown. However, there are some slight spelling errors.  @csmoore can you please fix then and reassign to me?

![image](https://cloud.githubusercontent.com/assets/5116835/26179301/cbf3ee20-3b17-11e7-977d-44053e686fb7.png)

**Comment by ACueva** [comment] 2017-05-17 22:59
FYI @csmoore 
https://github.com/Esri/visibility-addin-dotnet/blob/693a0f5f4aaa7bb63d8e5d2d0db659a96c571345/source/Visibility/VisibilityLibrary/Properties/Resources.resx

**Comment by csmoore** [comment] 2017-05-18 14:43
@NatalieCampos @ACueva - sorry about that :grimacing: - typo fixed in next build

**Comment by NatalieCampos** [comment] 2017-05-22 17:22
type has been fixed.  warning is as below.
https://nationalsecurity.esri.com/portal/home/

**Comment by NatalieCampos** [comment] 2017-05-22 17:55
The following caution was added to the "Using Radial Line of Sight" Xmetal topic.  Closing this issue.  

> The use of a global or large area extent image service will result in excessive processing  time.  It is recommended to use a local dataset or a small area extent image service.

**Comment by NatalieCampos** [comment] 2017-05-22 20:48
@csmoore I get the warning for LLOS.  I am unsure whether the warning was necessary for LLOS as all the issues related to the processing time and image services were with RLOS. I tested LLOS with the test image service on the national security portal and it ran real quick.  So is this warning necessary for LLOS? 

![image](https://cloud.githubusercontent.com/assets/5116835/26327657/15ff1ec8-3ef5-11e7-9c8a-9c29547408ea.png)

**Comment by csmoore** [comment] 2017-05-22 21:34
It probably isn't needed for the ArcMap LLOS (which uses a different method and seems to be faster) - it can be removed there if you like (that was the "**may** take a long time" part) - also hopefully it is not still misspelled

**Comment by NatalieCampos** [comment] 2017-05-22 21:55
@csmoore no it isnt misspeeled anymore... sorry i used the old screen grab.  Can we remove the warning for LLOS?  I feel like if the warning is unneeded meaning that the use of an image services for LLOS isnt slow... then lets not have it. I think it could cause the user to be hesitant about  using the tool.

**Comment by csmoore** [comment] 2017-05-23 13:29
Doing some more testing in ArcMap with this with a larger dataset and LOS over a larger area - 
http://www.arcgis.com/home/item.html?id=58a541efc59545e6b7137f961d7de883  - and I think the warning is still appropriate/advisable (it took 5 mins for me, over not a huge area) - but let me know if you still feel strongly about removing this warning.

![image](https://cloud.githubusercontent.com/assets/3090809/26356486/29a9c7a2-3f9a-11e7-9ee4-f301e0b52c74.png)

**Comment by NatalieCampos** [comment] 2017-05-23 16:06
@csmoore agreed.  Closing issue

**Closed by NatalieCampos** 2017-05-23 16:06 UTC
Labels: 4 - Done, B - Affects Documentation, B - Bug, effort-large, F - RLOS, priority - normal, V - 10.4.1
