### ISSUE TITLE
LLOS and RLOS fail if run immediately after adding point with Military Symbol Editor

### ISSUE THREAD

**Issue by BobBooth** [Esri/visibility-addin-dotnet#290] opened 2018-07-05 17:51 UTC
I'm seeing LLOS and RLOS fail when I have added points to the map using Military Symbol Editor Add to Map functionality.  
To repro:
Start a new project. 
Add a DEM (I used ElevationUTM_Zone10 from SDTC test data)
Open Military Symbol Editor. 
Open Visibility Pane.
Search for a keyword (I used "tank")
Choose a feature (I chose Vehicle : Tank : Heavy)
Add the schema.
Click Symbol tab, set the Identity/Affiliation (I used "Hostile/Faker")
Click Add to Map.
Add some points to the map.
Switch to the Visibility tab.
On the LLOS tab:
Click Input Points button for Observer points.
Add a couple points.
Click Input Points button for Target points.
Add a couple of points.
Click OK to run the LLOS process.
![image](https://user-images.githubusercontent.com/3801392/42338831-1c23e6a2-8059-11e8-94ac-8aeb7d8e06dc.png)
Fails.
Click OK,
Cancel/clear points.
Try again to do LLOS.
It works correctly:
![image](https://user-images.githubusercontent.com/3801392/42338917-6970c312-8059-11e8-96e5-7bb19d3f1962.png)

Repeat the same steps but using RLOS, and you get a similar issue:
![image](https://user-images.githubusercontent.com/3801392/42339163-2ff33632-805a-11e8-8429-2257bae6fe0e.png)
Clear and try again, and it works.
![image](https://user-images.githubusercontent.com/3801392/42339194-4958beb2-805a-11e8-9817-7b46f14e28c7.png)
@ACueva  @dfoll  @topowright

**Comment by BobBooth** [comment] 2018-07-05 17:57
@csmoore - this seems to be an issue with the interaction of the two tabs - Military Symbol Editor and Visibility. Looks like an edit session issue, seems to work OK if you click the Edit tab and save edits after adding the military features.

**Comment by csmoore** [comment] 2018-07-05 18:21
That is very odd indeed (esp. the "raster NO_DATA" error in the screenshot).

But to address we could prompt the user to Save or Cancels edits whenever the focus is removed from the Symbol Editor tab - this might be a helpful enhancement anyway.

**Comment by ACueva** [comment] 2018-07-05 18:49
I can confirm this same work-flow causes the same error for me the first time around.  If I save my edits prior to running the Visibility RLOS tool, the error does not appear.

**Comment by csmoore** [comment] 2018-08-17 13:10
@topowright @lfunkhouser - I am able to reproduce this problem *without* the Military Symbol Editor by just starting an edit session in a separate/different feature class and adding a few features - so perhaps it is some sort of geodatabase locking issue in Visibility.

The general problem seems to be if there are any other unsaved feature edits in the default GDB, visibility fails for some reason. 

It looks like this will need to be addressd in visibility. For example, if there are unsaved edits, we can prompt the user to save before running the tool. Would you like me to make this change in Visibility?

**Comment by topowright** [comment] 2018-08-29 14:27
The challenge with this issue is there is an open edit session that is keeping the addin from writing new features classes or feature datasets to the geodatabase. to fix this issue we need to close the edit session on the project database before we start our visibility workflow for LLOS and RLOS

**Comment by dfoll** [comment] 2018-11-05 19:35
MT build 126 or later should be able to be used to test this

**Comment by dfoll** [comment] 2018-11-05 19:53
Using MT build 126. 
1. Ran LLOS
2. Added some lines with DD
3. Added two units with MSE
4. Ran another LLOS.

no crashes or failures with any of the add-ins, or the last run of LLOS. @BobBooth can you check this out and comment if it is working correctly. If it is, we can proceed with doing appropriate documentation tasks

**Comment by BobBooth** [comment] 2018-11-05 20:35
@dfoll - I confirm that using MT build 126, I can add military symbols, switch to LLOS and run that for some points, switch back to add more military symbols, switch to RLOS and run those, no crashes or issues. I agree, we can move on to the doc tasks.

**Comment by BobBooth** [comment] 2018-12-14 18:39
Military Tools What's new
Moved issue 290 from known issues to issues addressed. https://github.com/esri/visibility-addin-dotnet/issues/290

Visibility January 2019
Moved issue 290 from known issues to issues addressed. https://github.com/esri/visibility-addin-dotnet/issues/290

**Comment by dfoll** [comment] 2019-01-09 17:50
- Confirmed issue is fixed with MT 176.
- Confirmed it is not listed as a known issue, and has been moved to Issues addressed.

**Closed** 2019-01-14 16:24 UTC
Labels: A-bug, B-moderate, CyberTech, E-verified, S-Military Tools, V -  Pro 2.1, V - MT 3.3, W-Defense Team
