### ISSUE TITLE
Linear Line of Sight produces no results if data frame coordinate system is changed in a session

### ISSUE THREAD

**Issue by BobBooth** [Esri/visibility-addin-dotnet#248] opened 2017-12-06 21:14 UTC
Doing checklist testing, I added the released Visibility Add-In (http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=2015) to the latest ArcMap 10.6 (8319).
I added SRTM 30 m data for the AOI from Military Tools test data. That raster is in GCS_WGS_1984
I attempted to use the Visibility LLOS tool on the data, but got the warning that it was not projected.
I changed the data frame coordinate system to World Mercator (linear units meters) and exported a copy of the raster in that, added it, used it as elevation source.
I can add points, but I do not see them (neither observers nor targets).
I can click OK to run the tool, and the data frame pans, but I see no results.

RLOS does work.

**Comment by BobBooth** [comment] 2017-12-06 21:15
@lfunkhouser  @topowright  @csmoore

**Comment by csmoore** [comment] 2017-12-07 16:56
@BobBooth - I seem to be able to reproduce this with some difficulty. It seems to be related to the step of actually changing the projection of the data frame. When this happens, none of the addins seems to be able to add graphics to the graphics container (though all other processing behaves as normal - you just can't see it). 

Here were my repro steps (10.6.8271):

1. Launch ArcMap
2. Add a local basemap: `C:\Program Files (x86)\ArcGIS\Desktop10.6\TemplateData\TemplateData.gdb\World\continent`
3. Add the elevation dataset from Military Tools Geoprocessing:
`military-tools-geoprocessing-toolbox-dev\testdata\MilitaryToolsTestData.gdb\ElevationUTM_Zone10`
4. Set the data frame to be in the same projection/SR as `ElevationUTM_Zone10`
5. Use one of the military tools addin map tools to drop a marker or line 
6. None of the addins seem to be able to drop marker/line graphics - though all other processing behaves as normal 
    a. All of the addins use very similar code - so it is possible that this is a bug there with a reproject or something

**Comment by BobBooth** [comment] 2017-12-07 17:23
@csmoore - thanks for narrowing it down - I confirm that is has to do with changing the data frame projection. I can use the same UTM-projected elevation data and the tool works, if I just add the projected data to the map.

**Comment by BobBooth** [comment] 2017-12-07 17:24
@csmoore  - updated the title.

**Comment by csmoore** [comment] 2017-12-07 21:40
This seems to be a GraphicsContainer bug at 10.6. I can reproduce this same issue with [the Graphics Container SDK sample](https://github.com/Esri/arcobjects-sdk-community-samples/tree/master/Net/Framework/CustomUIElements) :

1. Launch ArcMap
2. Add a local basemap: C:\Program Files (x86)\ArcGIS\Desktop10.6\TemplateData\TemplateData.gdb\World\continent
3. Set the Data Frame coordinate system to Projected | WGS 1984 Web Mercator (aux sphere)
4. Use the "Dharma Toolbar" from the SDK Custom UI elements sample to draw a line
5. Line does not draw after being added to GraphicsContainer
    a. Note: if you draw the line big enough (size of US) you can see a much bigger mis-projected line

@lfunkhouser @topowright - can we report this issue?

![image](https://user-images.githubusercontent.com/3090809/33739813-79824c22-db6c-11e7-9fc1-52c2ebce11d0.png)

**Comment by lfunkhouser** [comment] 2017-12-08 18:50
@ACueva please work with @csmoore to understand and follow up with this issue ASAP.

**Comment by ACueva** [comment] 2017-12-08 23:52
Spoke with POC: David B.

The feedback I received can be summed up to "Why are you running LOS on the world?".

@csmoore @BobBooth We need to test this further to see if what we actually encountered is more of a work-flow issue.  The part that does concern me is if bad values are entered, the behavior should not be that you can't do anything else with our tools.

Let's touch base on Monday to see if we can get a more detailed workflow, including exact projections used.  Also, we need to try to reproduce this on a previous version to see if this has always been an issue or something introduced at this release.

**Comment by BobBooth** [comment] 2017-12-11 18:36
This is a bug with 10.6 that is not present when using the Visibility Add-In with 10.3.1 (available on the test VM I had).
Steps to repro:
Add test data (n36.dt2) from solutions GP tools (military-tools-geoprocessing-toolbox/tree/dev/testdata/Elevation/Source/SRTM30M)
![image](https://user-images.githubusercontent.com/3801392/33846992-1af627f6-de77-11e7-8ff3-92895165b1b5.png)
The add-in gives "Please project your data" message.
The data was in WGS84:
![image](https://user-images.githubusercontent.com/3801392/33847085-6b179e86-de77-11e7-9565-f736240bb785.png)
Change data frame to UTM Z 11 N
![image](https://user-images.githubusercontent.com/3801392/33847112-8051b16a-de77-11e7-9648-f102af761b75.png)
Export raster with same projection as data frame (UTM).
Switch Visibility pane to using the projected (UTM) raster.
Tool works as expected:
![image](https://user-images.githubusercontent.com/3801392/33847157-a4fbc708-de77-11e7-8b23-af3cfd2db829.png)
In contrast, with 10.6, the data frame and elevation source can be set to UTM and the tool will add points, but you can't see them on the map. Run the tool, it seems to run, but no output is displayed.
![image](https://user-images.githubusercontent.com/3801392/33847343-2e274cd2-de78-11e7-9956-756ef2c9a425.png)

**Comment by BobBooth** [comment] 2017-12-11 18:37
@ACueva  your POC missed the point.
Not running it on the world.

**Comment by topowright** [comment] 2017-12-11 20:03
@ACueva I think the person you spoke with is David Burrows

**Comment by csmoore** [comment] 2017-12-11 20:25
The main point we wanted to make to them is that this same issue is present using the **SDK sample** if we change the map projection - [detailed steps with the ArcObjects SDK sample are above](https://github.com/Esri/visibility-addin-dotnet/issues/248#issuecomment-350102576)

**Comment by topowright** [comment] 2017-12-12 02:48
I am not able to reproduce this issue at 10.6 build 8321. My steps to check this issue is: 

1. Install the Visibility Add-In
2. Add the button to a toolbar
Open the add-in
Add the SRTM30 - n36.dt2 from the source testing folder
Drop points on the map
Attempt to run
Result: Your data is not projected
Remove the layer and add in the projected UTM Zone 10 layer from the Military Tools geodatabase
Remove the points in the LLOS tool
Attempt to un
Result: Your data frame is not projected
Reproject my data frame into UTM Zone10 projection
Remove the graphics in LLOS tool
Add more graphics 
Attempt to run the tool
Good results

**Comment by topowright** [comment] 2017-12-12 02:50
I would like to run thru this workflow with you @BobBooth and see your workflow as well. For now I am going to move this to verify being that I have not seen any movement on this through out the day.

**Comment by topowright** [comment] 2017-12-12 02:54
@BobBooth I just saw your comments that you cannot replicate this with 10.3.1 and I can no longer replicate this issue with 0.6 build 8321. I think this should be closed.

**Comment by BobBooth** [comment] 2017-12-12 16:47
@topowright - It is non-repro on 10.3.1, but it is definitely still a problem on 10.6 (just installed 8321, and it is failing in exactly the same way).
Steps to repro:
1) Add the n36.dt2 raster to the map. (data frame will be set to GCS_WGS_84)
2) Add observer and target points.
3) attempt to run - get  "please project" message.
4) Set the data frame coord system to a projected one (I used NAD_1983_UTM_Zone_11N)
5) Export the n36.dt2 layer using the data frame's coordinate system, add the results to the map.
6) Switch the Input Surface to the projected raster.
7) Click Cancel (clears input points)
8) Click Clear Graphics (clears graphics)
9) Add observer and target points. Note that they do not display, but they are added to the points lists in the Visibility window.
10)  Click OK.
The display zooms to the extent of the points you dropped, but no results show up, nor do the points you dropped.

@topowright  @csmoore

**Comment by topowright** [comment] 2017-12-12 22:05
I fully think this is an issue, but it is also a issue on 10.5.1. I am going to double check on 10.3.1

**Comment by topowright** [comment] 2017-12-13 05:19
I have double checked this exact workflow that @BobBooth found in 10.3.1 and it works just fine. Reaching out to the core person who deals with projections was not sure what this issue was. I have sent a issue to the sp-arcmap and I am waiting to see what comes of it.

**Comment by csmoore** [comment] 2017-12-14 19:52
@topowright - I added the location of the prebuilt SDK sample/addin to [the SDK sample repro steps above](https://github.com/Esri/visibility-addin-dotnet/issues/248#issuecomment-350102576)

**Comment by csmoore** [comment] 2018-02-27 19:08
@topowright @ACueva @dfoll - are you able to check with SDK folks to see if this issue (Graphic Elements do not reproject if data frame projection is changed in ArcMap 10.5+) to see if it is being tracked and provide an issue/bug `#`.

The traffic on this particular issue is a bit confusing, but the main point is that this is a problem in the SDK that can be [reproduced using the SDK samples as mentioned above](https://github.com/Esri/visibility-addin-dotnet/issues/248#issuecomment-350102576) and affects all of our ArcMap addins (they all use SDK graphic elements)

**Comment by BobBooth** [comment] 2018-02-27 19:15
Another manifestation of the problem can be seen in https://github.com/Esri/distance-direction-addin-dotnet/issues/527

**Comment by topowright** [comment] 2018-03-01 19:10
@BobBooth please explain your last comment. I am not sure how they are related.

**Comment by BobBooth** [comment] 2018-03-01 19:16
@topowright - it seems to be that the underlying problem in this issue and in https://github.com/Esri/distance-direction-addin-dotnet/issues/527 is the same - the add-in hangs on to the previous coordinate system when you change the coordinate system. This results in incorrect output. DD lines and Viz LLOS lines are both affected.

**Comment by csmoore** [comment] 2019-06-19 15:50
The good news is the underlying SDK issue seems **to be fixed at 10.7.1**, so this should now work at that version.

The bad news is that I noticed at 10.6.1 that the issue was much worse and showed up even if you opened an .mxd with a reprojected map (before if you saved the mxd and restarted ArcMap thing would work)

**Comment by lfunkhouser** [comment] 2019-06-20 14:45
Versions are not fully understood on this issue. From the comments in this issue, seems like it was a problem at 10.5.1, 10.6 and 10.6.1. What about 10.7, 10.5, 10.4.1, 10.4?
Adding `QC` label to determine what versions of ArcMap we are experiencing this issue. This affects documentation. Adding `Doc` labels.

**Comment by csmoore** [comment] 2019-06-20 14:50
If it helps, I know that this was a problem from 10.4.1 to 10.6.1 - the only version I am not sure about is whether it was fixed at 10.7 or 10.7.1

**Comment by dfoll** [comment] 2019-06-20 17:20
update known issue to list what versions it is broken at, then move back to product backlog

**Comment by dfoll** [comment] 2019-06-24 15:03
Works at :
- 10.7.1

**Comment by dfoll** [comment] 2019-06-24 16:08
Add topographic map
add utmelevationzone10
add some points
try to run
get error about needing to match
match them up (without clearing points)
in bad case, results will be in the middle of nowhere

**Comment by dfoll** [comment] 2019-06-24 17:11
@lfunkhouser @csmoore  I have tried several times to read and understand the comments on this issue. I feel that this issue has grown too unruly and difficult to easily diagnose and fix the problem. It seems that there was more going on with this issue that the SDK issue that was fixed at 10.7.1 as this problem is still happening. I would like to close this issue in favor #327

**Comment by lfunkhouser** [comment] 2019-06-26 01:45
@dfoll I think it is a problem that was introduced at 10.4, present at 10.5 and 10.6. It worked at 10.3.1, and worked again at 10.7/10.7.1. I don't want to close but rather investigate it as a team. I think the steps to reproduce are clear, the back and forth was just on the versions as I understand it.

**Comment by dfoll** [comment] 2019-06-26 12:06
@lfunkhouser sounds good. when we do look at this, i think we are just going to end up closing a few of them at one time as duplicates

**Comment by csmoore** [comment] 2019-07-31 16:56
This is a repeat of #327 - #327 issue was updated to cover the additional case mentioned here where Visibility Add Point Tool does not add points after the Coordinate System is changed.

The comment here covers the ArcMap versions that the problem is encountered / fixed on: 
https://github.com/Esri/visibility-addin-dotnet/issues/327#issuecomment-516572086

**Closed** 2019-08-19 15:04 UTC
Labels: A-bug, D-ArcMap, E-duplicate
