### ISSUE TITLE
RLOS errors with Image Service as input surface

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#21] opened 2016-03-07 22:59 UTC
RLOS tool is giving an error message when the input surface is an Image Service added to the map as an image service layer. For the test I'm using _Environment\D_DigitalTerrainModel_ under _http://afmcloud.esri.com/arcgis/services/Environment/D_DigitalTerrainModel/ImageServer_.

1) Open **Visibility** tools
2) Select **RLOS** tab
3) **Input Surface** select _Elevation\D_DigitalTerrianModel_
4) Use **Map Point Tool** to select one or two locations on the surface
5) Click **OK**

Error:
![image](https://cloud.githubusercontent.com/assets/3093182/13586343/1d73c2e8-e475-11e5-91cd-5bdab154e75a.png)

**Comment by dfoll** [comment] 2017-01-15 01:05
This works in the current version.

**Comment by dfoll** [comment] 2017-05-10 21:56
i used ...\NationalIntelligence\DigitalSurfaceModel to test this out on 10.5 using MilitaryTools build 1453, and i am still seeing this

**Comment by csmoore** [comment] 2017-05-11 16:10
For all of the image service issues ( #21 #184 #175) - we should probably come up with a consistent, agreed-upon approach. Probably the simplest thing to do in the short term is:

1. Publish a service with a smaller area of interest
2. Fix the bugs found with the case
3. Then add some sort of check to ensure the user doesn't try to do use the addin on too large of an area (maybe 2 X 2 degrees max) and add some doc/guidance.

**Comment by csmoore** [comment] 2017-05-18 17:48
This is a repeat/duplicate of #184 (which has more discussion) so closing

**Closed by csmoore** 2017-05-18 17:48 UTC
Labels: 0 - Backlog, B - Affects Documentation, B - Bug, B - Duplicate, B - Enhancement, effort-large, F - RLOS
