### ISSUE TITLE
Visibility - Observer Height Measurement Default

### ISSUE THREAD

**Issue by csmoore** [Esri/visibility-addin-dotnet#226] opened 2017-09-06 00:56 UTC
_From @joebayles on July 8, 2017 20:15_

### Widget
Visibility
### Version of widget
2.0
### Bug or Enhancement
Observer Height defaults to Kilometers
### Repo Steps or Enhancement details
Opened a brand new install of the visibility widget, observer height defaults to 2 kilometers:
![image](https://user-images.githubusercontent.com/5016557/27988748-0dd77146-63df-11e7-8c21-8a86f6eeeea2.png)

Suggest changing that to 2 meters.

#### FYI
@nfeuerstein @lfunkhouser 

_Copied from original issue: Esri/solutions-webappbuilder-widgets#922_

**Comment by csmoore** [comment] 2017-09-06 00:56
_From @topowright on July 8, 2017 20:19_

Good catch!

**Comment by csmoore** [comment] 2017-09-06 00:56
_From @adgiles on July 10, 2017 7:58_

Updated in dev branch

**Comment by csmoore** [comment] 2017-09-06 00:56
_From @lfunkhouser on July 10, 2017 23:7_

@adgiles Can you revert the change and create a branch for this change, naming it adg/#922-obs-height or something similiar. Thanks.

**Comment by csmoore** [comment] 2017-09-06 00:56
_From @adgiles on July 11, 2017 7:35_

@lfunkhouser change reverted and branch created, PR #923 waiting to be verified

**Comment by csmoore** [comment] 2017-09-06 00:56
_From @adgiles on August 14, 2017 17:17_

Please can somebody verify

**Comment by adgiles** [comment] 2017-12-01 09:54
Looks like this change has already made it into the dev branch of this repo, maybe when the repos were copied over. I think this issue is good to close.

**Comment by topowright** [comment] 2018-01-10 22:22
Verified : 
![image](https://user-images.githubusercontent.com/5488313/34798619-a7862b92-f611-11e7-9dad-f56515bdb301.png)

**Comment by garys-esri** [comment] 2018-03-20 20:09
Did you try actually running the widget though? It treats the observer height as kilometers unless I change it in the dropdown.

By the way, when I go to change it in the dropdown, it suddenly switches from Meters to Kilometers:

![visibility-widget-bug](https://user-images.githubusercontent.com/3091666/37679932-c948a840-2c58-11e8-88e8-7a0b753ce40e.gif)

I do not see this behavior in your sample app at https://nationalsecurity.esri.com/solutionsweb/Visibility/. I don't know if it's a different version of the Web AppBuilder, a different version of the Visibility widget, or something else. I am using the [dev branch](https://github.com/Esri/visibility-addin-dotnet/tree/dev), currently at commit 26590c6a374ae192462cc8c09cefe1d0df54e094.

**Comment by garys-esri** [comment] 2018-03-21 14:37
This is easily reproduced in plain old Dojo outside of Web AppBuilder:

https://jsfiddle.net/m6ts0wq6/30/

The fix is to clone the `options` object before giving it to the second select:

https://jsfiddle.net/m6ts0wq6/31/

I recommend re-opening this issue, since it was not fully resolved previously. I will submit a pull request shortly that fixes it.

**Comment by garys-esri** [comment] 2018-03-21 15:12
Pull request #278 fixes this bug.

**Comment by lfunkhouser** [comment] 2018-03-21 19:25
Thanks @garys-esri - I'm Reopening the issue. 

@kgonzago please do a thorough review to understand the issue and comment on the details of the out-of-sync behavior @garys-esri is experiencing between what is released, what is in GitHub and what is in the sample app. Add comments to the PR upon merging for clarity.

**Comment by lfunkhouser** [comment] 2018-06-21 15:49
FYI: @dfoll @topowright @ACueva 
Reopening to ensure testing was done on this issue that was merged by @kgonzago

**Comment by topowright** [comment] 2018-06-21 15:56
This is now been tested from our dev branch as of today. This is what is now seen: 
![image](https://user-images.githubusercontent.com/5488313/41730588-04cad9c6-7531-11e8-9bf7-7937fc15b610.png)

**Comment by topowright** [comment] 2018-06-21 17:10
Looking at this closer it is still an issue. I am able to replicate this in the current release from Dev. @kgonzago am I missing something that you can help me with?

**Comment by kgonzago** [comment] 2018-06-25 11:51
@topowright I can work with you on this.

**Comment by kgonzago** [comment] 2018-06-25 19:00
Verified this issue was fixed:
![image](https://user-images.githubusercontent.com/6391826/41869916-860715e0-7888-11e8-9746-6526ea71aab9.png)

**Closed** 2018-07-02 16:54 UTC
Labels: A-feature, E-verified, V - WAB
