### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#256] opened 2018-01-30 05:47 UTC
These are the missing items for dark theme support
- [ ] Properties dialog box for Save as
- [ ] Save as button
- [ ] Cancel button
![image](https://user-images.githubusercontent.com/5488313/35550135-f50f504c-053d-11e8-8b81-e87a73e30ec6.png)

**Comment by topowright** [comment] 2018-02-05 15:13
@csmoore  where are we on this task? Can you give an update being that this has been in progress for a couple of days with no comments.

**Comment by csmoore** [comment] 2018-02-05 15:22
This task is progressing, code was moved from library project into the Pro project and is running in branch: https://github.com/Esri/visibility-addin-dotnet/tree/csm/%23256-dark-theme-redesign

Remaining things to do:

1. Test for errors
2. Fix the Simple Buttons 
3. Fix the settings window

So hopefully this will be done today. Here is how it looks now (buttons still need fixed `#2 above`):

![image](https://user-images.githubusercontent.com/3090809/35811988-ce5f891a-0a5d-11e8-9201-60c24e44eae0.png)

**Comment by csmoore** [comment] 2018-02-06 19:19
Just a status update, this is working as intended now in branch: https://github.com/Esri/visibility-addin-dotnet/tree/csm/%23256-dark-theme-redesign 

Before submitting a PR to dev, I'm just going to spend a little time to see if something similar could have been done without forking the code in the common library

![image](https://user-images.githubusercontent.com/3090809/35877465-55131694-0b43-11e8-903f-fb4f110c7317.png)

![image](https://user-images.githubusercontent.com/3090809/35877518-7ab02e5a-0b43-11e8-9e65-3da9c1573ecb.png)

**Comment by csmoore** [comment] 2018-02-07 14:18
Just to update the current status - the plan is to spend some time (timeboxed 1.5 days) looking at 2 approaches:

1. Forking all of the code from VisibilityLibrary and adding to the ProAppVisibilityModule project - in branches/changes: https://github.com/Esri/visibility-addin-dotnet/compare/csm/%23256-dark-theme-redesign

2. Just setting the buttons to transparent (which was also the only solution that worked in `#1` above)  - in branches/changes: https://github.com/Esri/visibility-addin-dotnet/compare/dev...csm/%23253-dark-theme-buttons 
    1. To see if the `#2` approach can be improved to create the child windows in the Pro theme/context to address this issue (screenshot below)

![image](https://user-images.githubusercontent.com/3090809/35921098-bc7c80e6-0be7-11e8-9b54-b2395247de21.png)

**Comment by csmoore** [comment] 2018-02-08 17:48
After looking at this, we were able to go with Option `#2` [above](https://github.com/Esri/visibility-addin-dotnet/issues/256#issuecomment-363782500) - addressed in PR #261 

Should be ready to QA/QC/test after review/merge

**Comment by topowright** [comment] 2018-02-13 20:32
Linking these issues as they are the exact same problem: 
https://github.com/Esri/distance-direction-addin-dotnet/issues/482

![image](https://user-images.githubusercontent.com/5488313/36172180-ea6c25f2-10b9-11e8-82a0-aca36f015d22.png)

**Closed** 2018-02-14 01:28 UTC
Labels: F - Dark Theme, G-Documentation, G-QA Create (Checklist), G-QC Verify (Checklist)
